name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Modelica
      run: |
        for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` nightly"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
        wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
        apt-key fingerprint
        sudo apt update
        sudo apt install openmodelica
    - name: Perform metric tests
      run: |
        echo Current dir is: $(pwd)
        omc $(pwd)/CI/OpenModelica/compile.mos

